//----------------------------------------------------------------------
// MNPCTableEnglish.cpp
//----------------------------------------------------------------------
// Generated by tools/i18n/npc_gen.pl - do not edit by hand.
//
// The name shown over an NPC and the one-line description of its role
// come from Data/Info/NPC.inf, which ships in Korean. This table is the
// English translation, applied over the loaded table so the English
// client does not depend on English game data. Edit tools/i18n/npc.en.tsv
// and regenerate.
//----------------------------------------------------------------------

#include "Client_PCH.h"
#include "MNPCTableEnglish.h"

#include "MNPCTable.h"

namespace {

struct NPC_STRING {
	unsigned int	NPCID;
	const char*		pName;			// NULL keeps the name the file supplied
	const char*		pDescription;	// NULL keeps the description
};

const NPC_STRING	s_EnglishNPC[] = {
	{    11, "Drake", "Sells ARs and SGs" },
	{    12, "Spartan", "Sells SMGs" },
	{    13, "Singh", "Healing, sells potions and magazines" },
	{    14, "Nuwa", "Blade skill training, sells blades" },
	{    15, "Jean", "Gun skill training, sells SRs" },
	{    16, "Jacques", "Issues weapons" },
	{    17, "Kaiser", "Briefings and missions, event quests" },
	{    18, "Cain", "Librarian" },
	{    20, "Kevin", "Storage sales and management" },
	{    21, "Chris", "Storage sales and management, quests" },
	{    22, "Christine", "Storage sales and management" },
	{    23, "Kreif", "Sells accessories" },
	{    24, "Han", "Sword skill training, sells swords" },
	{    25, "Hannibal", "Enchant skill training, sells maces" },
	{    26, "Tanya", "Computer operator" },
	{    27, "David", "Repairs" },
	{    92, "Vrykolakas", "Vampire skill training" },
	{    93, "Carpatini", "Sells transformation items and Seals, Storage sales and management, quests" },
	{    94, "Valerie", "Sells Coats" },
	{    95, "Gruber", "Sells necklaces, bracelets and rings" },
	{    96, "Griffin", "Repairs" },
	{    97, "Sandra", "Sells body armor, leg armor, belts and helmets" },
	{    98, "Salamander", "Healing, sells potions and magazines" },
	{    99, "Sonya", "Sells body armor, leg armor, belts and helmets" },
	{   100, "Yoshihara", "Sells boots and gloves" },
	{   101, "Johan", "Healing, sells potions and magazines" },
	{   102, "Crow", "Sells boots and gloves" },
	{   103, "Smith", "Restores Alignment" },
	{   108, "Smirovich", "Repairs, silver plating" },
	{   109, "Jack", "Sells motorcycles and magazines, motorcycle care" },
	{   110, "Hasbro", "Sells shields, silver plating" },
	{   157, "Conan", "Restores Alignment" },
	{   158, "Frederick", "Advancement weapon exchange" },
	{   159, "Yevgeny", "Sells accessories, couple registration" },
	{   160, "Nikolai", "Sells body armor, leg armor, belts and helmets" },
	{   161, "Richardson", "Sells boots and gloves" },
	{   162, "Chamor", "Sells accessories" },
	{   163, "Rachmaninov", "Healing skill training, sells crosses" },
	{   164, "Stoyanov", "Restores Alignment" },
	{   219, "Seth", "Sells accessories" },
	{   220, "Kakon", "Repairs, sells accessories and transformation items" },
	{   250, "Matthew", "Helicopter travel" },
	{   251, "Skip", "Helicopter travel" },
	{   253, "Barun", "Repairs, respawn point, revenue and Storage management" },
	{   254, "Hunt", "Repairs, respawn point, revenue and Storage management" },
	{   255, "Rebecca", "Sells Vampire weapons and Beads, event quests" },
	{   296, "Yamamoto", "Healing, sells potions and magazines" },
	{   297, "Dennis", "Healing, sells potions and magazines" },
	{   298, "Mark", "Field Headquarters guard" },
	{   299, "John", "Field Headquarters guard" },
	{   300, "Lisa", "Field Headquarters guard" },
	{   302, "Terry", "Sells boots, gloves and shields" },
	{   303, "Nancy", "Sells tops, bottoms, belts and hats" },
	{   304, "Fabian", "Field Headquarters guard" },
	{   305, "Jeff", "Field Headquarters guard" },
	{   306, "Octavus Helper 1", "Castle Siege attacker support" },
	{   307, "Octavus Helper 2", "Castle Siege defender support" },
	{   315, "Tristan", "Field Headquarters guard" },
	{   316, "Ellen", "Field Headquarters guard" },
	{   317, "Patricia", "Field Headquarters guard" },
	{   362, "Agnes", "Sells Coats" },
	{   363, "Aiman", "Sells transformation items, Serums and Seals, storage and repairs" },
	{   364, "Caim", "Sells weapons and Beads, Vampire skill training" },
	{   365, "Priya", "Sells accessories, couple registration" },
	{   368, "Larva", "Restore" },
	{   370, "Raven", "Sells Vampire Coats" },
	{   427, "Griffith", "Sells Serums, transformation items and Seals, repairs and storage" },
	{   428, "Robin", "Sells accessories, repairs and storage" },
	{   429, "Murphy", "Buys and sells items" },
	{   430, "Carmen", "Healing, buys and sells items" },
	{   516, "Marie", "Sells accessories, war enlistment" },
	{   517, "Moloch", "Sells items, resets Rank skills" },
	{   518, "Beatrix", "Sells items, resets Rank skills" },
	{   519, "Eileen", "Sells items, healing, resets Rank skills" },
	{   520, "Amy", "Sells Coats, war enlistment" },
	{   521, "Allen", "Sells weapons, war enlistment" },
	{   522, "Judith", "Sells items, sets evacuation point" },
	{   523, "Harold", "Repairs, sells armor, resets Rank skills" },
	{   524, "Brenda", "Information, war enlistment, revenue and Storage management" },
	{   525, "Simone", "Repairs, respawn point, revenue and Storage management" },
	{   551, "Praoros", "Octavus Castle statue" },
	{   553, "Arioch", "Septimus Castle statue" },
	{   555, "Fafnir", "Tertius Castle statue" },
	{   557, "Immortality", "Quartus Castle statue" },
	{   653, "Lavinia", "Rare quests, respawn point, event quests" },
	{   654, "Ripati", "Healing, sells items" },
	{   655, "Manescu", "Sells weapons, adjusts Alignment" },
	{   656, "Sioram", "Item repairs, Guild matters, PK zone travel" },
	{   657, "Amata", "Sells items, Storage sales and management" },
	{   658, "Hora", "Sells clothing" },
	{   674, "Piscate", "Grants entry to Hexserius Castle" },
	{   675, "Minescence", "Grants entry to Pentanus Castle" },
	{   676, "Lepri", "Buys and sells items, information search" },
	{   677, "Elunia", "Buys and sells items, war enlistment" },
	{   678, "Ignium", "Repairs and storage" },
	{   679, "Naishas", "Buys and sells items, information search" },
	{   680, "Nitrisha", "Buys and sells items, war enlistment" },
	{   681, "Rowa", "Repairs and storage" },
	{   749, "Tertius Helper 1", "Castle Siege attacker support" },
	{   750, "Tertius Helper 2", "Castle Siege defender support" },
	{   751, "Pentanus Helper 1", "Castle Siege attacker support" },
	{   752, "Pentanus Helper 2", "Castle Siege defender support" },
	{   821, "Argonas", "Dungeon travel guide" },
	{   822, "Belegost", "Dungeon travel guide" },
	{   823, "Ea", "Dungeon travel guide" },
	{   804, "Mikliz", "Entry to the lowest level of Laom Dungeon" },
	{   833, "Training Camp Instructor", "Training Camp entry guide" },
	{   872, "Gonbenis", "Reconnaissance agent" },
	{   882, "Bernado", "Dungeon entrance statue" },
};

}	// namespace

//----------------------------------------------------------------------
// Apply English NPC Table
//----------------------------------------------------------------------
void
ApplyEnglishNPCTable()
{
	if (g_pNPCTable == NULL)
	{
		return;
	}

	for (const NPC_STRING& row : s_EnglishNPC)
	{
		MNPCTable::iterator found = g_pNPCTable->find(row.NPCID);
		if (found == g_pNPCTable->end() || found->second == NULL)
		{
			continue;
		}

		if (row.pName != NULL)
		{
			found->second->Name = row.pName;
		}
		if (row.pDescription != NULL)
		{
			found->second->Description = row.pDescription;
		}
	}
}
