if(NOT EXISTS "${POLICY_FILE}")
    message(FATAL_ERROR "Missing generated warning policy: ${POLICY_FILE}")
endif()
file(STRINGS "${POLICY_FILE}" targets)
# Both language contexts matter: a C-only adapter must get the same policy.
string(REPLACE "-CXX.txt" "-C.txt" c_policy_file "${POLICY_FILE}")
if(NOT EXISTS "${c_policy_file}")
    message(FATAL_ERROR "Missing generated C warning policy: ${c_policy_file}")
endif()
file(STRINGS "${c_policy_file}" c_targets)
list(APPEND targets ${c_targets})
list(LENGTH targets target_count)
if(target_count LESS 10)
    message(FATAL_ERROR "Warning policy inventory unexpectedly small: ${target_count}")
endif()
if(COMPILER_STYLE STREQUAL "CLANG_CL")
    set(required /clang:-Wall /clang:-Wextra /clang:-Wundef)
elseif(COMPILER_STYLE STREQUAL "MSVC")
    set(required /W3 /w14311 /w14312 /w14668)
else()
    set(required -Wall -Wextra -Wundef)
endif()
foreach(target IN LISTS targets)
    foreach(flag IN LISTS required)
        string(FIND " ${target} " " ${flag} " position)
        if(position EQUAL -1)
            message(FATAL_ERROR "Missing ${flag}: ${target}")
        endif()
    endforeach()
endforeach()
message(STATUS "Warning policy verified on ${target_count} compiled targets")
