#!/usr/bin/perl
#-----------------------------------------------------------------------------
# npc_gen.pl - generate the English NPC table override
#-----------------------------------------------------------------------------
# Reads the NPC names and descriptions dumped by npc_dump.pl and the
# translation table beside it, and writes Client/MNPCTableEnglish.cpp: one row
# per NPC whose name or description has an English translation.
#
#	npc.ko.tsv   npcID, spriteID, name, description        (generated)
#	npc.en.tsv   korean, english                            (hand written)
#
# The translation table is keyed by the Korean text: names and descriptions
# share it, and a description that several NPCs share is translated once.
#
#	perl npc_gen.pl <npc.ko.tsv> <npc.en.tsv> <out.cpp>
#-----------------------------------------------------------------------------

use strict;
use warnings;

my ($koPath, $enPath, $outPath) = @ARGV;
die "usage: $0 <npc.ko.tsv> <npc.en.tsv> <out.cpp>\n"
	unless defined $koPath && defined $enPath && defined $outPath;

my %english;
open my $en, '<:raw', $enPath or die "$enPath: $!\n";
my $enLine = 0;
while (my $line = <$en>) {
	$enLine++;
	$line =~ s/\r?\n\z//;
	next if $line !~ /\t/;    # a line without a tab is a comment
	my ($korean, $text) = split /\t/, $line, 2;
	die "$enPath:$enLine: duplicate entry\n" if exists $english{$korean};
	die "$enPath:$enLine: translation is not ASCII\n" if $text =~ /[^\x00-\x7F]/;
	$english{$korean} = $text;
}
close $en;

sub literal {
	my ($s) = @_;
	$s =~ s/"/\\"/g;
	return $s;
}

my (@rows, %missing, $npcs);
open my $ko, '<:raw', $koPath or die "$koPath: $!\n";
my $koLine = 0;
while (my $line = <$ko>) {
	$koLine++;
	$line =~ s/\r?\n\z//;
	next if $line eq '';
	my ($id, $sprite, $name, $description) = split /\t/, $line, 4;
	die "$koPath:$koLine: expected four tab separated columns\n" unless defined $description;
	$npcs++;
	my @text;
	for my $field ($name, $description) {
		if ($field eq '' || $field !~ /[^\x00-\x7F]/) {
			push @text, 'NULL';
		}
		elsif (exists $english{$field}) {
			push @text, '"' . literal($english{$field}) . '"';
		}
		else {
			$missing{$field} = 1;
			push @text, 'NULL';
		}
	}
	next if $text[0] eq 'NULL' && $text[1] eq 'NULL';
	push @rows, sprintf("\t{ %5d, %s, %s },", $id, @text);
}
close $ko;

open my $out, '>:raw', $outPath or die "$outPath: $!\n";
print $out <<'HEADER';
//----------------------------------------------------------------------
// MNPCTableEnglish.cpp
//----------------------------------------------------------------------
// Generated by tools/i18n/npc_gen.pl - do not edit by hand.
//
// The name shown over an NPC and the one-line description of its role
// come from Data/Info/NPC.inf, which ships in Korean. This table is the
// English translation, applied over the loaded table so the English
// client does not depend on English game data. Edit tools/i18n/npc.en.tsv
// and regenerate.
//----------------------------------------------------------------------

#include "Client_PCH.h"
#include "MNPCTableEnglish.h"

#include "MNPCTable.h"

namespace {

struct NPC_STRING {
	unsigned int	NPCID;
	const char*		pName;			// NULL keeps the name the file supplied
	const char*		pDescription;	// NULL keeps the description
};

const NPC_STRING	s_EnglishNPC[] = {
HEADER
print $out join("\n", @rows), "\n";
print $out <<'FOOTER';
};

}	// namespace

//----------------------------------------------------------------------
// Apply English NPC Table
//----------------------------------------------------------------------
void
ApplyEnglishNPCTable()
{
	if (g_pNPCTable == NULL)
	{
		return;
	}

	for (const NPC_STRING& row : s_EnglishNPC)
	{
		MNPCTable::iterator found = g_pNPCTable->find(row.NPCID);
		if (found == g_pNPCTable->end() || found->second == NULL)
		{
			continue;
		}

		if (row.pName != NULL)
		{
			found->second->Name = row.pName;
		}
		if (row.pDescription != NULL)
		{
			found->second->Description = row.pDescription;
		}
	}
}
FOOTER
close $out;

printf STDERR "%d NPCs, %d rows written, %d distinct strings still Korean\n",
	$npcs // 0, scalar @rows, scalar keys %missing;
print STDERR "  $_\n" for sort keys %missing;
