#!/usr/bin/perl
#-----------------------------------------------------------------------------
# npcscript_gen.pl - generate the English NPC script override table
#-----------------------------------------------------------------------------
# Reads the Korean strings dumped by npcscript_dump.pl and the translation table
# beside it, and writes Client/MNPCScriptTableEnglish.cpp: one row per slot of
# NPCScript.inf that has an English translation.
#
#	npcscript.ko.tsv   id, kind, index, owner, korean          (generated)
#	npcscript.en.tsv   korean, english                         (hand written)
#
# The translation table is keyed by the Korean text rather than by position, so
# the 2646 slots collapse to the ~2000 distinct lines that actually need
# translating, and a slot whose text has no entry keeps whatever NPCScript.inf
# supplied. Both files use the escaping npcscript_dump.pl applies.
#
#	perl npcscript_gen.pl <npcscript.ko.tsv> <npcscript.en.tsv> <out.cpp>
#-----------------------------------------------------------------------------

use strict;
use warnings;

my ($koPath, $enPath, $outPath) = @ARGV;
die "usage: $0 <npcscript.ko.tsv> <npcscript.en.tsv> <out.cpp>\n"
	unless defined $koPath && defined $enPath && defined $outPath;

#-----------------------------------------------------------------------------
# Translation table
#-----------------------------------------------------------------------------
my %english;

open my $en, '<:raw', $enPath or die "$enPath: $!\n";
my $enLine = 0;

while (my $line = <$en>) {
	$enLine++;
	$line =~ s/\r?\n\z//;
	next if $line eq '' || $line =~ /^#/;

	my ($korean, $text) = split /\t/, $line, 2;
	die "$enPath:$enLine: expected two tab separated columns\n" unless defined $text;
	die "$enPath:$enLine: duplicate entry\n" if exists $english{$korean};

	$english{$korean} = $text;
}

close $en;

#-----------------------------------------------------------------------------
# C++ string literal
#-----------------------------------------------------------------------------
# The input carries the dump's escapes, so \n and friends are already the two
# characters C++ wants. Only the quote needs escaping on the way out, and a byte
# the dump wrote as \xNN has to stay separated from a following hex digit.
sub literal {
	my ($s) = @_;
	$s =~ s/"/\\"/g;
	$s =~ s/(\\x[0-9a-f]{2})([0-9a-fA-F])/$1" "$2/g;
	return $s;
}

#-----------------------------------------------------------------------------
# Rows
#-----------------------------------------------------------------------------
my @rows;
my %missing;
my $slots = 0;

open my $ko, '<:raw', $koPath or die "$koPath: $!\n";
my $koLine = 0;

while (my $line = <$ko>) {
	$koLine++;
	$line =~ s/\r?\n\z//;
	next if $line eq '';

	my ($id, $kind, $index, $owner, $korean) = split /\t/, $line, 5;
	die "$koPath:$koLine: expected five tab separated columns\n" unless defined $korean;

	$slots++;

	if (!exists $english{$korean}) {
		$missing{$korean} = 1;
		next;
	}

	push @rows, sprintf("\t{ %6d, '%s', %2d, \"%s\" },", $id, $kind, $index, literal($english{$korean}));
}

close $ko;

#-----------------------------------------------------------------------------
# Output
#-----------------------------------------------------------------------------
open my $out, '>:raw', $outPath or die "$outPath: $!\n";

print $out <<'HEADER';
//----------------------------------------------------------------------
// MNPCScriptTableEnglish.cpp
//----------------------------------------------------------------------
// Generated by tools/i18n/npcscript_gen.pl - do not edit by hand.
//
// Every line an NPC speaks comes from Data/Info/NPCScript.inf, which ships
// in Korean. This table is the English translation of it, applied over the
// loaded table so the English client does not depend on English game data.
// Edit tools/i18n/npcscript.en.tsv and regenerate.
//----------------------------------------------------------------------

#include "Client_PCH.h"
#include "MNPCScriptTableEnglish.h"

#include "MNPCScriptTable.h"

//----------------------------------------------------------------------
// NPC_SCRIPT_STRING
//----------------------------------------------------------------------
// One slot of one script: the subject is what the NPC says, the contents
// are the replies the player picks from.
//----------------------------------------------------------------------
namespace {

struct NPC_SCRIPT_STRING {
	unsigned int	ScriptID;
	char			Kind;			// 'S' subject, 'C' content
	int				Index;
	const char*		pText;
};

const NPC_SCRIPT_STRING	s_EnglishScript[] = {
HEADER

print $out join("\n", @rows), "\n";

print $out <<'FOOTER';
};

}	// namespace

//----------------------------------------------------------------------
// Apply English NPC Script Table
//----------------------------------------------------------------------
// Called after NPCScript.inf is loaded. A script id or slot the shipped data
// does not have is skipped, so a data file that has moved on from this table
// keeps its own text instead of being corrupted by it.
//----------------------------------------------------------------------
void
ApplyEnglishNPCScriptTable()
{
	if (g_pNPCScriptTable==NULL)
	{
		return;
	}

	const int count = sizeof(s_EnglishScript) / sizeof(s_EnglishScript[0]);

	for (int i=0; i<count; i++)
	{
		const NPC_SCRIPT_STRING& entry = s_EnglishScript[i];

		NPC_SCRIPT* pScript = g_pNPCScriptTable->GetData( entry.ScriptID );

		if (pScript==NULL)
		{
			continue;
		}

		NPC_SCRIPT::STRING_TABLE& table = (entry.Kind=='S')
			? pScript->SubjectTable
			: pScript->ContentTable;

		if (entry.Index < 0 || entry.Index >= table.GetSize())
		{
			continue;
		}

		table.Set(entry.Index, entry.pText);
	}
}
FOOTER

close $out;

printf STDERR "%s: %d of %d slots translated, %d distinct lines still Korean\n",
	$outPath, scalar @rows, $slots, scalar keys %missing;
