//----------------------------------------------------------------------
// test_wire_layout.cpp
//----------------------------------------------------------------------
//
// Wire-layout inventory: packet id, name and max body size for every
// packet factory under Client/Packet, regenerated on each run from the
// real factory objects and compared to the committed
// tests/wire-layout.txt.
//
// The server repo (../server) produces the identical file from its own
// packet classes, and this client carries a hand-maintained copy of
// every one of them. The two inventories are the first mechanical
// check that the copies still agree; server/tests/tools/
// wire_inventory_diff.sh diffs them. A change in this file is a
// wire-protocol change: it must ship in both repos together.
//
// The factory registry is tests/generated/WireInventory.inc, produced
// by tests/tools/gen_wire_inventory.pl and pinned by the
// wire_inventory_fresh ctest: one include and one registration per
// factory class, the same shape as the server's AllPacketFactories.inc.
// Constructing every factory and its packet here is also the link-level
// proof that every packet class in every direction - the written CG/CL
// ones included - lives in the packetwire library with no reach into
// the executable (docs/RESTRUCTURING.md task 2.5; task 2.4's
// test_packet_factories.cpp proves the received directions through
// PacketFactoryManager).
//
// Rpackets (CR*/RC*) are registered but flagged out of the rendered
// file: the server deleted its copies, and the file must stay line for
// line diffable against the server's.
//
// Set UPDATE_GOLDENS=1 in the environment to re-record the inventory
// instead of comparing.
//
//----------------------------------------------------------------------

#include "test_framework.h"
#include "SocketInputStream.h"

#include "Packet.h"
#include "PacketFactory.h"
#include "PacketFactoryManager.h"
#include "Exception.h"

#define WIRE_INVENTORY_INCLUDES
#include "WireInventory.inc"
#undef WIRE_INVENTORY_INCLUDES

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace {

struct FactoryEntry
{
	FactoryEntry(const char* n, PacketFactory* f, bool i)
		: name(n), factory(f), inventoried(i) {}

	const char*	name;
	PacketFactory*	factory;
	bool		inventoried;	// in tests/wire-layout.txt (see the header)
};

//----------------------------------------------------------------------
// Owns the factories for one test body; the framework has no fixtures.
//----------------------------------------------------------------------
class AllFactories
{
public:
	AllFactories()
	{
#define WIRE_INVENTORY_ENTRIES
#include "WireInventory.inc"
#undef WIRE_INVENTORY_ENTRIES
	}

	~AllFactories()
	{
		for (size_t i = 0; i < factories.size(); i++)
			delete factories[i].factory;
	}

	std::vector<FactoryEntry>	factories;

private:
	AllFactories(const AllFactories&);
	AllFactories& operator=(const AllFactories&);
};

struct InventoryEntry
{
	std::string	name;
	PacketSize_t	maxSize;
};

//----------------------------------------------------------------------
// Same rendering as server/tests/wire_layout_test.cpp, so the two files
// diff line for line. Every factory takes part in the id-conflict scan;
// only the inventoried ones land in the map that gets rendered.
//----------------------------------------------------------------------
std::map<PacketID_t, InventoryEntry>	BuildInventory(const std::vector<FactoryEntry>& factories,
						       std::vector<std::string>& idConflicts)
{
	std::map<PacketID_t, InventoryEntry> inventory;
	std::map<PacketID_t, std::string> claimed;
	for (size_t i = 0; i < factories.size(); i++)
	{
		const PacketID_t id = factories[i].factory->getPacketID();
		const std::string name = factories[i].name;

		std::map<PacketID_t, std::string>::iterator existing = claimed.find(id);
		if (existing != claimed.end())
		{
			if (existing->second != name)
			{
				std::ostringstream conflict;
				conflict << "packet ID " << id << " claimed by both "
					 << existing->second << " and " << name;
				idConflicts.push_back(conflict.str());
			}
			continue;
		}
		claimed[id] = name;

		if (!factories[i].inventoried)
			continue;
		InventoryEntry entry;
		entry.name = name;
		entry.maxSize = factories[i].factory->getPacketMaxSize();
		inventory[id] = entry;
	}
	return inventory;
}

std::string	RenderInventory(const std::map<PacketID_t, InventoryEntry>& inventory)
{
	std::ostringstream out;
	out << "# Wire-layout inventory: packet-id<TAB>name<TAB>max-body-size\n";
	out << "# Generated by test_wire_layout (UPDATE_GOLDENS=1 to re-record).\n";
	out << "# A diff in this file is a wire-protocol change: the server repo's\n";
	out << "# packet classes must ship the identical change.\n";
	for (std::map<PacketID_t, InventoryEntry>::const_iterator it = inventory.begin();
	     it != inventory.end(); ++it)
	{
		out << it->first << "\t" << it->second.name << "\t" << it->second.maxSize << "\n";
	}
	return out.str();
}

// True only when UPDATE_GOLDENS is exactly "1", so UPDATE_GOLDENS=0
// compares instead of silently re-recording.
bool	IsRecording()
{
	const char* value = std::getenv("UPDATE_GOLDENS");
	return value != NULL && std::strcmp(value, "1") == 0;
}

// Print the first line that differs, since CHECK cannot show strings.
void	ReportFirstDifference(const std::string& expected, const std::string& actual)
{
	std::istringstream e(expected);
	std::istringstream a(actual);
	std::string el, al;
	int line = 0;
	while (true)
	{
		const bool he = static_cast<bool>(std::getline(e, el));
		const bool ha = static_cast<bool>(std::getline(a, al));
		line++;
		if (!he && !ha)
			return;
		if (he != ha || el != al)
		{
			std::fprintf(stderr,
				"  wire-layout.txt line %d differs:\n    committed: %s\n    actual:    %s\n",
				line, he ? el.c_str() : "<end of file>", ha ? al.c_str() : "<end of file>");
			return;
		}
	}
}

} // namespace

TEST(WireLayout, PacketIdsAreUniqueAcrossAllFactories)
{
	AllFactories all;
	CHECK(all.factories.size() > 0);
	std::vector<std::string> idConflicts;
	BuildInventory(all.factories, idConflicts);
	for (size_t i = 0; i < idConflicts.size(); i++)
		std::fprintf(stderr, "  %s\n", idConflicts[i].c_str());
	CHECK_EQ(0, idConflicts.size());
}

TEST(WireLayout, InventoryMatchesCommittedFile)
{
	AllFactories all;
	std::vector<std::string> idConflicts;
	const std::map<PacketID_t, InventoryEntry> inventory = BuildInventory(all.factories, idConflicts);
	const std::string actual = RenderInventory(inventory);

	const char* path = WIRE_LAYOUT_FILE;
	if (IsRecording())
	{
		std::ofstream file(path, std::ios::trunc | std::ios::binary);
		CHECK(file.good());
		file << actual;
		std::printf("recorded %s (%d packets)\n", path, (int)inventory.size());
		// A recording run must not read as a green comparison.
		CHECK(!"recorded tests/wire-layout.txt - rerun without UPDATE_GOLDENS to compare");
		return;
	}

	std::ifstream file(path, std::ios::binary);
	CHECK(file.good());	// missing: run once with UPDATE_GOLDENS=1 to record
	std::stringstream expected;
	expected << file.rdbuf();
	// Written in binary, read in binary: a CRLF checkout would still
	// differ, which .gitattributes prevents (eol=lf on the file).
	const bool same = expected.str() == actual;
	if (!same)
	{
		std::fprintf(stderr,
			"  the wire-layout inventory drifted from %s - review the diff as a\n"
			"  protocol change (it must ship in the server repo too) and re-record\n"
			"  with UPDATE_GOLDENS=1\n", path);
		ReportFirstDifference(expected.str(), actual);
	}
	CHECK(same);
}

//----------------------------------------------------------------------
// Every factory creates its packet, and the packet reports the id its
// factory does: a createPacket/getPacketID mismatch would misroute at
// dispatch time. This is also the link proof for the written
// directions (CG/CL), which no PacketFactoryManager ever constructs.
//----------------------------------------------------------------------
TEST(WireLayout, EveryFactoryCreatesAPacketWithItsOwnId)
{
	AllFactories all;
	CHECK(all.factories.size() > 0);
	for (size_t i = 0; i < all.factories.size(); i++)
	{
		const FactoryEntry& entry = all.factories[i];
		CHECK(static_cast<std::uint64_t>(entry.factory->getPacketMaxSize()) + szPacketHeader < MaxSocketInputBufferSize / 4);
		Packet* pPacket = entry.factory->createPacket();
		const bool bCreated = pPacket != NULL;
		const bool bSameId = bCreated && pPacket->getPacketID() == entry.factory->getPacketID();
		if (!bCreated || !bSameId)
			std::fprintf(stderr, "  %s: %s\n", entry.name,
				     bCreated ? "packet id differs from its factory's" : "createPacket returned NULL");
		CHECK(bCreated);
		CHECK(bSameId);
		delete pPacket;
	}
}

//----------------------------------------------------------------------
// The client's PacketFactoryManager is the receive-side registry: every
// id it serves must be one of these factories, sized as that factory
// sizes it. A registration whose factory is missing from the generated
// list would be a packet the validator bounds but nothing inventories
// (the server pins the same relation from its ratchet script).
//----------------------------------------------------------------------
TEST(WireLayout, EveryManagerRegistrationIsAnInventoriedFactory)
{
	AllFactories all;
	std::map<PacketID_t, const FactoryEntry*> byId;
	for (size_t i = 0; i < all.factories.size(); i++)
		byId[all.factories[i].factory->getPacketID()] = &all.factories[i];

	PacketFactoryManager manager;
	manager.init();

	size_t registered = 0;
	for (PacketID_t id = 0; id < Packet::PACKET_MAX; id++)
	{
		PacketSize_t maxSize;
		try {
			maxSize = manager.getPacketMaxSize(id);
		} catch (InvalidProtocolException&) {
			continue;	// not registered on the client
		}
		registered++;

		std::map<PacketID_t, const FactoryEntry*>::const_iterator it = byId.find(id);
		const bool bListed = it != byId.end();
		const bool bSameSize = bListed && it->second->factory->getPacketMaxSize() == maxSize;
		if (!bListed)
			std::fprintf(stderr, "  packet id %u is registered but no factory in WireInventory.inc has it\n",
				     (unsigned)id);
		else if (!bSameSize)
			std::fprintf(stderr, "  %s: manager max size %u, factory %u\n", it->second->name,
				     (unsigned)maxSize, (unsigned)it->second->factory->getPacketMaxSize());
		CHECK(bListed);
		CHECK(bSameSize);
	}
	CHECK(registered > 0);
}
